### ISSUE TITLE
Make option to send internal metrics to carbon server

### ISSUE THREAD

**Issue by Nyoroon** [go-graphite/graphite-clickhouse#10]
Make option to send internal metrics (requests, memory etc) to carbon server (like carbonapi, go-carbon and carbon-clickhouse does).

**Comment by lomik** [comment]
graphite-clickhouse doesn't have metrics. This only in todo

**Comment by Felixoid** [comment]
Hey. I'd like to implement it, so the suggestions on what metrics are necessary to implement are very appreciated!

**Comment by msaf1980** [comment]
First iteration of metrics in https://github.com/go-graphite/graphite-clickhouse/pull/194

**Comment by msaf1980** [comment]
First iteartion for gch metrics is done in current master. For me is done, i completely remove logstash for collect metrics from logs.
If more metrics is needed, you can reopen a issue.
