### ISSUE TITLE
Purpose of filter "Path in metrics_list"

### ISSUE THREAD

**Issue by MalKeshar** [go-graphite/graphite-clickhouse#183]
After upgrading from 0.11.7 to 0.13.2 on test server we found that sql requests for datapoins now have additional filter "WHERE (Path in metrics_list)".
Documentation lacks description of it. In the source code present some comment on this subject:
// name of external-data table with metrics pathsconst extTableName = "metrics_list"

Checking for metrics name already present an executed in the index table. Can you please reveal the purpose os this filter? Why do we need query to additional table, which name is hardcoded in the source code and whose behavior don't customize in any way?

**Comment by MalKeshar** [comment]
I see now. It temporary table for caching purposes.

**Comment by Felixoid** [comment]
It's not caching, but rather a bit more optimal way to pass a metrics list than a query arguments. Previously it may be a 1kk long query for some big globe. Now it's passed as a file/temporary table.

**Comment by Felixoid** [comment]
https://github.com/go-graphite/graphite-clickhouse/pull/100 here it was implementers

**Comment by MalKeshar** [comment]
Thank you. Found out the reason, but miss this pull request. Interesting to see benchmarks.
