### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mvk981** [go-graphite/graphite-clickhouse#250]
Hi, 
we get errors like:

Oct 20 16:35:06 graphite-clickhouse[2681667]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 20 16:35:06 graphite-clickhouse[2681667]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13a02e3]
Oct 20 16:35:06 graphite-clickhouse[2681667]: goroutine 192 [running]:
Oct 20 16:35:06 graphite-clickhouse[2681667]: github.com/lomik/graphite-clickhouse/render/data.(*commonStep).doneTarget(...)
Oct 20 16:35:06 graphite-clickhouse[2681667]:         /home/runner/work/graphite-clickhouse/graphite-clickhouse/render/data/common_step.go:26
Oct 20 16:35:06 graphite-clickhouse[2681667]: github.com/lomik/graphite-clickhouse/render/data.(*query).getDataPoints(0xc0004e48c0, {0x1b21908?, 0xc00028df80?}, 0xc0006aa000)
Oct 20 16:35:06 graphite-clickhouse[2681667]:        /home/runner/work/graphite-clickhouse/graphite-clickhouse/render/data/query.go:134 +0x2c3
Oct 20 16:35:06 graphite-clickhouse[2681667]: github.com/lomik/graphite-clickhouse/render/data.(*MultiTarget).Fetch.func1(0xc000566120?)
Oct 20 16:35:06 graphite-clickhouse[2681667]:         /home/runner/work/graphite-clickhouse/graphite-clickhouse/render/data/multi_target.go:118 +0x8a
Oct 20 16:35:06 graphite-clickhouse[2681667]: created by github.com/lomik/graphite-clickhouse/render/data.(*MultiTarget).Fetch
Oct 20 16:35:06 graphite-clickhouse[2681667]:         /home/runner/work/graphite-clickhouse/graphite-clickhouse/render/data/multi_target.go:116 +0x5ae

after this graphite-clickhouse crash with error

graphite-clickhouse --version
0.13.4

**Comment by msaf1980** [comment]
Fixed in master

**Comment by Hipska** [comment]
Still seems to be existing: #295
