### ISSUE TITLE
graphite-clickhouse 0.13+ - not support tree-table?

### ISSUE THREAD

**Issue by syatihoko** [go-graphite/graphite-clickhouse#274]
Hello.
From Notes v13: DEPRECATION: tree-table is deprecated, consider migration to the index table.

I tried to set up the old table structure (tree-table). Tell me, it doesn't  longer supported?
As I understand, the last version that worked was version 12?

**Comment by bzed** [comment]
@syatihoko I fail to understand what your problem is. You are doing a new setup with something thats deprecated since a few years and then complain that it doesn't work?!?

**Comment by bzed** [comment]
Hi @syatihoko! Even if its still supported somehow, I would not use it. Its gone for good.

https://github.com/go-graphite/graphite-clickhouse/blob/master/doc/index-table.md has the documentation on how to migrate the old tables into the new one. Its very painless as current metrics will show up in the index table as soon as they are inserted anyway.
