### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by Hipska** [go-graphite/graphite-clickhouse#277]
The current released version [v0.13.4](https://github.com/go-graphite/graphite-clickhouse/releases/tag/v0.13.4) dates from Nov '22 and since then over 100 commits to master have been done..

So I'm wondering if (and when) it becomes time to publish a new release?

**Comment by msaf1980** [comment]
@Hipska After smaller time new relase is planned.

**Comment by Hipska** [comment]
@msaf1980 What do you mean with that?

**Comment by jonnydh** [comment]
Hey @msaf1980 👋  Any update on an expected release time please? :) Very interested in a fix for https://github.com/go-graphite/graphite-clickhouse/issues/178

**Comment by Hipska** [comment]
Seems like a new version is in the making: #289

**Comment by mchrome** [comment]
Released [v0.14.0](https://github.com/go-graphite/graphite-clickhouse/releases/tag/v0.14.0)
